### ISSUE TITLE
Error running the progress-tracker-frontend locally

### ISSUE THREAD

**Issue by gowthamshankar99** [aws-samples/aws-step-functions-progress-tracking#18]
When running the progress-tracker-frontend locally, getting the following error 

```
Error: ENOENT: no such file or directory, open '/Users/gothamsh/aws-step-functions-progress-tracking/progress-tracker-frontend/.next/BUILD_ID'
    at async open (node:internal/fs/promises:637:25)
    at async Object.readFile (node:internal/fs/promises:1246:14)
    at async setupFsCheck (/opt/homebrew/lib/node_modules/next/dist/server/lib/router-utils/filesystem.js:145:19)
    at async initialize (/opt/homebrew/lib/node_modules/next/dist/server/lib/router-server.js:62:23)
    at async Server.<anonymous> (/opt/homebrew/lib/node_modules/next/dist/server/lib/start-server.js:247:36) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/gothamsh/aws-step-functions-progress-tracking/progress-tracker-frontend/.next/BUILD_ID'
}
```

**Comment by alparamonov** [comment]
Pull request merged
